### ISSUE TITLE
Remove Serilog dependency

### ISSUE THREAD

**Issue by shersh** [berdon/Orleans.Providers.Redis#28]
It would be better to use Microsoft abstraction ILogger for logging purpose and give users to configure loggin solution itself

**Comment by berdon** [comment]
The Microsoft ILogger abstraction is nice but it's simplicity means more advanced features like property interpolation are impossible.

**Comment by shersh** [comment]
Could you explain, what do you mean about "property interpolation" ?

**Comment by berdon** [comment]
Have a look at the serilog readme at https://github.com/serilog/serilog.

You do something like:
```c#
var position = new { Latitude = 25, Longitude = 134 };
var elapsedMs = 34;

log.Information("Processed {@Position} in {Elapsed} ms.", position, elapsedMs);
```

Which then allows you to access `Properties.Position` and `Properties.Elapsed` depending on how you want to process your logs. You can use a JSON "sink" and emit out actual JSON and retain the properties or you can use a more traditional "sink" that just logs out the formatted message.
