### ISSUE TITLE
Redist channel per subscription

### ISSUE THREAD

**Issue by shersh** [berdon/Orleans.Providers.Redis#29]
Why do you use HashRing channels instead of channel per subscription? 

For example we have 
```
my-cluster:some_provider_name-1
my-cluster:some_provider_name-2
my-cluster:some_provider_name-3
```

for all messages

and redis publish to these channels. 

But maybe it will be better for performance to publish and subsribe to individual channel for example:
`my-cluster:stream_namespace:client_guid`

?

**Comment by berdon** [comment]
It's possible; I certainly didn't do any performance analysis comparing the HashRing implementation versus using individual Redis channels. To be honest, this provider was fashioned after the Azure one and it's entirely possible the HashRing itself isn't necessary.

However, I remember there was something preventing just straight using Redis channels for stream channels. I think Orleans' stream implementation assumes control of the subscription and deliverance of messages and doesn't expose a means of handling it yourself. I could be wrong though.

I wouldn't be opposed to making this change but we're using this library in a rather large scale product and the redis streams are performing well. Have you observed any failures or issues with performance?
